// Tailwind build config for the Sa'ei dashboard. The design tokens below are
// lifted from the Stitch "Sa'ei" project's exported screens (same palette,
// type scale and spacing names), so class names copied from a Stitch export
// work here unchanged.
//
// The dashboard ships the COMPILED output (tailwind.css) as a static file --
// no CDN, no runtime JS. After changing classes in any .html/.js file, rebuild:
//
//   npx tailwindcss@3 -c tailwind.config.js -i tailwind.src.css -o tailwind.css --minify
//
// (run from this frontend/ folder).

module.exports = {
  content: ["./*.html", "./*.js"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#291800",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e6e2dc",
        "outline-variant": "#ddc0b8",
        "on-secondary-fixed-variant": "#00504b",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        secondary: "#0a6a64",
        "surface-tint": "#9f4120",
        "inverse-surface": "#31302c",
        "on-secondary": "#ffffff",
        "surface-bright": "#fdf9f2",
        "surface-container-low": "#f7f3ec",
        surface: "#fdf9f2",
        tertiary: "#805200",
        "secondary-fixed-dim": "#86d4cc",
        "primary-fixed": "#ffdbd0",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#1c1c18",
        outline: "#8a726b",
        "surface-variant": "#e6e2dc",
        "surface-dim": "#ddd9d3",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f4f0ea",
        "on-primary-fixed-variant": "#802a0a",
        "tertiary-fixed-dim": "#fdba5a",
        "on-background": "#1c1c18",
        "on-tertiary-container": "#fffbff",
        "primary-container": "#bc5633",
        error: "#ba1a1a",
        "surface-container-high": "#ece8e1",
        "on-secondary-container": "#17706a",
        "on-surface-variant": "#56423c",
        "on-error": "#ffffff",
        "on-primary-container": "#fffbff",
        "on-tertiary-fixed-variant": "#633f00",
        "inverse-primary": "#ffb59e",
        "surface-container": "#f2ede7",
        "primary-fixed-dim": "#ffb59e",
        "on-primary-fixed": "#3a0b00",
        "secondary-container": "#a2f1e8",
        primary: "#9c3e1e",
        "secondary-fixed": "#a2f1e8",
        "on-secondary-fixed": "#00201e",
        "tertiary-container": "#a06908",
        "tertiary-fixed": "#ffddb4",
        background: "#fdf9f2",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "3rem",
        "gutter-desktop": "1.5rem",
        "margin-tablet": "2rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        margin: "1rem",
        gutter: "1rem",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "Segoe UI", "Tahoma", "system-ui", "sans-serif"],
        mono: ["ui-monospace", "SFMono-Regular", "Consolas", "monospace"],
      },
      fontSize: {
        "display-lg": ["44px", { lineHeight: "52px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-xl-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.03em", fontWeight: "500" }],
      },
      boxShadow: {
        xs: "0 1px 2px rgba(28, 28, 24, 0.04)",
        soft: "0 1px 8px rgba(0, 0, 0, 0.04)",
      },
    },
  },
  plugins: [],
};
