"""
Dashboard + control API. Most endpoints are read-only views over the SQLite
DB the agents write to (models.py/db.py); a few (settings, CV upload) let the
frontend write configuration back to disk for a single local user.

Run with: uvicorn api:app --reload --port 8000
"""
import importlib
import json
import os
from collections import Counter
from pathlib import Path
from typing import Optional

from fastapi import FastAPI, File, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

import config
import cv_parser
import env_store
from agents import email_agent
from db import get_session, init_db
from models import Job, Application, SkillGap, NewsDigest, EmailLog, ReportLog

app = FastAPI(title="Job Application Agent API")

# Tighten allow_origins to your deployed frontend's exact origin before going live.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)

init_db()

CV_DIR = Path("cv")
CV_ALLOWED_EXTENSIONS = {".pdf", ".docx"}
CV_OUTPUT_DIR = Path("cv_output")
CV_OUTPUT_DIR.mkdir(exist_ok=True)

# Serves tailored CVs generated by the rewrite step -- lets the CV page's
# "download" links point straight at the file instead of proxying bytes
# through a dedicated endpoint.
app.mount("/files/cv-rewrites", StaticFiles(directory=str(CV_OUTPUT_DIR)), name="cv-rewrites")


@app.get("/api/health")
def health():
    return {"status": "ok"}


@app.get("/api/status")
def status():
    return {
        "dry_run": config.DRY_RUN,
        "whitelisted_sources": sorted(config.WHITELISTED_SOURCES),
        "llm_provider": config.LLM_PROVIDER,
    }


@app.get("/api/stats")
def stats():
    with get_session() as session:
        total_jobs = session.query(Job).count()
        total_apps = session.query(Application).count()
        pending = session.query(Application).filter(Application.status == "pending_review").count()
        auto_submitted = session.query(Application).filter(Application.status == "auto_submitted").count()
        emails_sent = session.query(Application).filter(Application.email_sent.is_(True)).count()
    return {
        "total_jobs": total_jobs,
        "total_applications": total_apps,
        "pending_review": pending,
        "auto_submitted": auto_submitted,
        "emails_sent": emails_sent,
    }


@app.get("/api/applications")
def list_applications(limit: int = 100, status: Optional[str] = None):
    with get_session() as session:
        query = session.query(Application, Job).join(Job, Application.job_id == Job.id)
        if status:
            query = query.filter(Application.status == status)
        rows = query.order_by(Application.date_created.desc()).limit(limit).all()
        return [
            {
                "id": a.id,
                "title": j.title,
                "company": j.company,
                "source": j.source_site,
                "url": j.url,
                "ats_score": a.ats_score,
                "status": a.status,
                "cv_path": a.cv_version_path,
                "email_sent": a.email_sent,
                "date_created": a.date_created.isoformat() if a.date_created else None,
                "date_applied": a.date_applied.isoformat() if a.date_applied else None,
            }
            for a, j in rows
        ]


@app.get("/api/skill-gaps")
def skill_gaps(limit: int = 20):
    with get_session() as session:
        rows = session.query(SkillGap).order_by(SkillGap.date_created.desc()).limit(500).all()
    counts = Counter()
    for row in rows:
        try:
            skills = json.loads(row.missing_skills)
        except (TypeError, json.JSONDecodeError):
            skills = []
        counts.update(skills)
    return [{"skill": skill, "count": count} for skill, count in counts.most_common(limit)]


@app.get("/api/news")
def news(limit: int = 5):
    with get_session() as session:
        rows = session.query(NewsDigest).order_by(NewsDigest.date_created.desc()).limit(limit).all()
    return [
        {
            "field": r.field,
            "content": r.content,
            "date_created": r.date_created.isoformat() if r.date_created else None,
        }
        for r in rows
    ]


# ---- settings: LLM provider + API key -------------------------------------

class SettingsUpdate(BaseModel):
    llm_provider: str
    gemini_api_key: Optional[str] = None
    ollama_model: Optional[str] = None
    ollama_base_url: Optional[str] = None


@app.get("/api/settings")
def get_settings():
    return {
        "llm_provider": config.LLM_PROVIDER,
        "ollama_model": config.OLLAMA_MODEL,
        "ollama_base_url": config.OLLAMA_BASE_URL,
        # Never echo the real key back to the frontend -- just whether one is set.
        "gemini_api_key_set": bool(config.GEMINI_API_KEY),
    }


@app.post("/api/settings")
def update_settings(body: SettingsUpdate):
    if body.llm_provider not in ("ollama", "gemini"):
        raise HTTPException(400, "llm_provider must be 'ollama' or 'gemini'")

    updates = {"LLM_PROVIDER": body.llm_provider}
    if body.ollama_model:
        updates["OLLAMA_MODEL"] = body.ollama_model
    if body.ollama_base_url:
        updates["OLLAMA_BASE_URL"] = body.ollama_base_url
    if body.gemini_api_key:
        updates["GEMINI_API_KEY"] = body.gemini_api_key

    if body.llm_provider == "gemini" and not body.gemini_api_key and not config.GEMINI_API_KEY:
        raise HTTPException(400, "GEMINI_API_KEY is required the first time you switch to gemini")

    env_store.update_env_file(updates)

    # Apply immediately to this running process (so GET /api/settings reflects
    # the change right away). The scheduler runs as a separate OS process and
    # only picks up .env changes on its next restart -- surfaced to the user
    # in the response rather than silently pretending it's already live there.
    for key, value in updates.items():
        os.environ[key] = value
    importlib.reload(config)

    return {
        "saved": True,
        "restart_required_for": ["scheduler"],
        **get_settings(),
    }


# ---- CV upload --------------------------------------------------------------

def _cv_status_payload() -> dict:
    cv_path = cv_parser.find_default_cv(str(CV_DIR))
    if not cv_path:
        return {"has_cv": False}

    path = Path(cv_path)
    stat = path.stat()
    payload = {
        "has_cv": True,
        "filename": path.name,
        "size_bytes": stat.st_size,
        "modified": stat.st_mtime,
    }
    try:
        text = cv_parser.parse_cv(cv_path)
        payload["preview"] = text.strip()[:400]
        payload["char_count"] = len(text)
    except Exception as exc:  # noqa: BLE001 -- surface any parse failure to the UI, don't crash the endpoint
        payload["parse_error"] = str(exc)
    return payload


@app.get("/api/cv/status")
def cv_status():
    return _cv_status_payload()


@app.post("/api/cv/upload")
async def cv_upload(file: UploadFile = File(...)):
    suffix = Path(file.filename or "").suffix.lower()
    if suffix not in CV_ALLOWED_EXTENSIONS:
        raise HTTPException(400, f"Unsupported file type '{suffix}' -- upload a .pdf or .docx")

    CV_DIR.mkdir(exist_ok=True)

    # Only one active CV at a time -- clear any previous current_cv.* first
    # so daily_run.py's auto-detection never picks up a stale file.
    for existing in CV_DIR.glob("current_cv.*"):
        existing.unlink()

    dest = CV_DIR / f"current_cv{suffix}"
    contents = await file.read()
    dest.write_bytes(contents)

    return _cv_status_payload()


@app.get("/api/cv/rewrites")
def cv_rewrites(limit: int = 50):
    with get_session() as session:
        rows = (
            session.query(Application, Job)
            .join(Job, Application.job_id == Job.id)
            .filter(Application.cv_version_path.isnot(None))
            .order_by(Application.date_created.desc())
            .limit(limit)
            .all()
        )
        return [
            {
                "application_id": a.id,
                "job_title": j.title,
                "company": j.company,
                "ats_score": a.ats_score,
                "download_url": f"/files/cv-rewrites/{Path(a.cv_version_path).name}",
                "date_created": a.date_created.isoformat() if a.date_created else None,
            }
            for a, j in rows
        ]


# ---- email: Gmail auth + sent log -------------------------------------------

@app.get("/api/email/status")
def email_status():
    return {
        "credentials_configured": email_agent.credentials_configured(),
        "authenticated": email_agent.is_authenticated(),
    }


@app.post("/api/email/authenticate")
def email_authenticate():
    if not email_agent.credentials_configured():
        raise HTTPException(
            400,
            f"No Gmail OAuth client file at {config.GMAIL_CREDENTIALS_JSON}. "
            "Download one from Google Cloud Console (OAuth client ID, Desktop app "
            "type) first, then try again.",
        )
    try:
        # Blocks this request until the browser tab it opens completes Google's
        # consent screen (or the flow times out) -- expected for a local tool.
        email_agent.get_gmail_service()
    except Exception as exc:  # noqa: BLE001 -- surface the real OAuth error to the UI
        raise HTTPException(400, f"Authentication failed: {exc}")
    return {"authenticated": True}


@app.get("/api/emails")
def list_emails(limit: int = 100):
    with get_session() as session:
        rows = (
            session.query(EmailLog, Application, Job)
            .outerjoin(Application, EmailLog.application_id == Application.id)
            .outerjoin(Job, Application.job_id == Job.id)
            .order_by(EmailLog.sent_at.desc())
            .limit(limit)
            .all()
        )
        return [
            {
                "id": e.id,
                "to_email": e.to_email,
                "subject": e.subject,
                "status": e.status,
                "dry_run": e.dry_run,
                "gmail_message_id": e.gmail_message_id,
                "error_message": e.error_message,
                "sent_at": e.sent_at.isoformat() if e.sent_at else None,
                "job_title": j.title if j else None,
                "company": j.company if j else None,
            }
            for e, a, j in rows
        ]


class SendEmailRequest(BaseModel):
    to_email: str
    subject: str
    body: str


@app.post("/api/applications/{application_id}/send-email")
def send_application_email_endpoint(application_id: int, body: SendEmailRequest):
    with get_session() as session:
        application = session.query(Application).filter(Application.id == application_id).first()
        if not application:
            raise HTTPException(404, "Application not found")

        cv_path = application.cv_version_path or cv_parser.find_default_cv(str(CV_DIR))
        if not cv_path:
            raise HTTPException(400, "No CV available to attach -- upload one on the CV page first")

        try:
            result = email_agent.send_application_email(body.to_email, body.subject, body.body, cv_path)
            status = "dry_run" if result.get("dry_run") else "sent"
            session.add(EmailLog(
                application_id=application.id,
                to_email=body.to_email,
                subject=body.subject,
                gmail_message_id=result.get("gmail_message_id"),
                dry_run=result.get("dry_run", config.DRY_RUN),
                status=status,
            ))
            if status == "sent":
                application.email_sent = True
                application.status = "sent"
            return {"status": status, "gmail_message_id": result.get("gmail_message_id")}
        except Exception as exc:  # noqa: BLE001 -- log the failure, still report it to the caller
            session.add(EmailLog(
                application_id=application.id,
                to_email=body.to_email,
                subject=body.subject,
                dry_run=config.DRY_RUN,
                status="failed",
                error_message=str(exc),
            ))
            session.commit()
            raise HTTPException(500, f"Failed to send email: {exc}")


# ---- reports: daily/weekly send history -------------------------------------

@app.get("/api/reports")
def list_reports(limit: int = 50):
    with get_session() as session:
        rows = session.query(ReportLog).order_by(ReportLog.sent_at.desc()).limit(limit).all()
    return [
        {
            "id": r.id,
            "report_type": r.report_type,
            "content": r.content,
            "status": r.status,
            "dry_run": r.dry_run,
            "error_message": r.error_message,
            "sent_at": r.sent_at.isoformat() if r.sent_at else None,
        }
        for r in rows
    ]
